---
# tasks file for roles/app
- name: launch proxy
  docker_container:
    name: proxy
    image: lucasthorelcpe/tp-devops-cpe:rproxy2
    networks:
      - name: "network_one"
    ports:
    - "80:80"