name: CI DevOps 2022 CPE
on:
#to begin you want to launch this job in main and develop
  push:
    branches: 
      - main
  pull_request:
jobs:
  test-backend:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
        #TODO
    #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify --file apibackend/simple-api/pom.xml