name: CI devops 2022 CPE
on:
  push:
    branches:
      - main
      - master
  pull_request:
jobs:
  test-backend:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.3.3
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
    - name: Build and test with Maven
      run: mvn clean verify --file /apibackend/MultistageBuild/simple-api/pom.xml
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./apibackend/MultistageBuild
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-cpe:simple-api
      - name: Build image and push database
      - name: Build image and push httpd

